### ISSUE TITLE
如何确认使用某个类型的编解码器

### ISSUE THREAD

**Issue by yinchengjian** [smallnest/goframe#4]
我发现我现在的消息满足
3 bytes length field at the beginning of 5 bytes header, do not strip header
这个格式，但是不知道要用哪一个编解码器
希望可以得到解答

**Comment by smallnest** [comment]
消息定义格式你得知道啊，否则你一个字节流你怎么能推断出来呢

**Comment by yinchengjian** [comment]
我知道格式，length+header+body这种格式，第一个length是int类型占4个字节，表示的是head+body的长度，head是一个标识位，占3个字节，body是消息主体，现在要用哪个，你这我看定义了4个，我不知道用哪一个

**Comment by smallnest** [comment]
lengthFieldOffset   = 0
 lengthFieldLength   = 4
 lengthAdjustment    = 0
 initialBytesToStrip = 0 (= do not strip header)

**Comment by smallnest** [comment]
这样读取出来header+body

**Comment by yinchengjian** [comment]
ok，我刚看明白，这个参数是用来配置lengthFieldBasedFrameConn这个对象，其他三种conn是用于其他消息格式的，感谢大佬，学到了
